name: Wechat Dest Version

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      download_link:
        description: 'The manual WeChatWin.exe download link'
        required: false
        default: 'https://dldir1v6.qq.com/weixin/Universal/Windows/WeChatWin.exe'

jobs:
  save_new_wechat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Test Github Action Server Time
      #   run: echo `date`
      - name: Check new version and push
        env: 
          GHTOKEN: ${{ secrets.GHTOKEN }}
          GH_TOKEN: ${{ github.token }}
        run: bash -x ./scripts/destVersionRelease.sh ${{ github.event.inputs.download_link }}
